import { useState } from 'react';
import { CheckCircle2, AlertTriangle, Building2, ExternalLink, Award, FileText, TrendingUp, TrendingDown, Volume2, Pause, Play, Square, Headphones, Mail } from 'lucide-react';
import { useToast } from '../contexts/ToastContext';

import CompetitorNotes from './CompetitorNotes';

function extractBulletPointsFromSection(markdown, sectionKeywords) {
  if (!markdown || typeof markdown !== 'string') return [];

  const sections = markdown.split(/\n(?=##\s+)/);
  for (const sec of sections) {
    const lines = sec.trim().split('\n');
    const headerLine = lines[0] || '';
    
    const isMatch = sectionKeywords.some(kw => headerLine.toLowerCase().includes(kw.toLowerCase()));
    if (isMatch) {
      const bullets = [];
      for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (line.startsWith('-') || line.startsWith('*') || /^\d+\./.test(line)) {
          const cleanText = line.replace(/^[-*\d.]+\s*/, '').trim();
          if (cleanText) {
            bullets.push(cleanText);
          }
        }
      }
      if (bullets.length > 0) return bullets;
    }
  }

  return [];
}

export default function ComparativeMatrix({ selectedCompetitor, userProfile, latestReport, intelligenceData }) {
  const toast = useToast();
  const [activeTab, setActiveTab] = useState('matrix');
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [isPausedAudio, setIsPausedAudio] = useState(false);

  if (!selectedCompetitor) {
    return (
      <div className="glass-card rounded-2xl p-10 text-center space-y-4 neon-border animate-fade-in-up">
        <div className="w-16 h-16 rounded-2xl bg-white/[0.02] border border-white/[0.04] flex items-center justify-center mx-auto">
          <Building2 className="w-8 h-8 text-slate-700" />
        </div>
        <h3 className="text-base font-bold text-slate-300 font-display">No Target Selected</h3>
        <p className="text-xs text-slate-500 max-w-sm mx-auto">
          Select a competitor from the sidebar to view the side-by-side comparative intelligence matrix.
        </p>
      </div>
    );
  }

  const companyName = userProfile?.company_name || 'Your Company';
  const companyUrl = userProfile?.company_url || selectedCompetitor.company_url || 'https://mycompany.com';
  const competitorName = selectedCompetitor.name || 'Competitor';
  const competitorUrl = selectedCompetitor.pricing_url || selectedCompetitor.domain || 'N/A';

  const reportSummary = latestReport?.summary || '';
  const technographics = intelligenceData?.technographics || [];

  // Text-to-Speech SpeechSynthesis Audio Listener Handler
  const handleSpeakBrief = () => {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
      toast.warning('Text-to-speech listening is not supported in this browser.', 'Browser Unsupported');
      return;
    }

    if (isPlayingAudio && !isPausedAudio) {
      window.speechSynthesis.pause();
      setIsPausedAudio(true);
      return;
    }

    if (isPausedAudio) {
      window.speechSynthesis.resume();
      setIsPausedAudio(false);
      return;
    }

    window.speechSynthesis.cancel(); // Stop any ongoing speech

    // Format markdown text for clean speech reading
    const cleanText = reportSummary
      .replace(/#+/g, '')
      .replace(/\*+/g, '')
      .replace(/\|/g, ' ')
      .replace(/\[.*?\]\(.*?\)/g, '')
      .replace(/`{1,3}.*?`{1,3}/gs, '')
      .trim();

    if (!cleanText) return;

    const utterance = new SpeechSynthesisUtterance(cleanText);
    utterance.rate = 1.0;
    utterance.pitch = 1.0;

    utterance.onstart = () => {
      setIsPlayingAudio(true);
      setIsPausedAudio(false);
    };

    utterance.onend = () => {
      setIsPlayingAudio(false);
      setIsPausedAudio(false);
    };

    utterance.onerror = () => {
      setIsPlayingAudio(false);
      setIsPausedAudio(false);
    };

    window.speechSynthesis.speak(utterance);
  };

  const handleStopAudio = () => {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
    setIsPlayingAudio(false);
    setIsPausedAudio(false);
  };

  const handleMailBrief = () => {
    if (!reportSummary) return;
    const subject = `Executive Intelligence Brief: ${competitorName} vs ${companyName}`;
    const cleanBrief = reportSummary
      .replace(/#+/g, '')
      .replace(/\*+/g, '')
      .replace(/\|/g, ' ')
      .trim();
    const body = `Executive Intelligence Brief:\nTarget: ${competitorName}\n\n${cleanBrief.slice(0, 1500)}\n\n---\nGenerated by Autonomous Competitive Intelligence Network`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };

  return (
    <div className="glass-card rounded-2xl p-6 neon-border space-y-6 animate-fade-in-up">
      {/* Header Battle Banner */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-white/[0.04] pb-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 rounded-lg bg-indigo-500/10 border border-indigo-500/10 text-[10px] font-semibold text-indigo-400 uppercase tracking-wider">
              Comparative Matrix
            </span>
            {selectedCompetitor.domain && (
              <span className="px-2 py-0.5 rounded-lg bg-emerald-500/10 border border-emerald-500/10 text-[10px] font-mono text-emerald-400">
                {selectedCompetitor.domain}
              </span>
            )}
          </div>
          {/* VS Title */}
          <h2 className="text-lg font-bold text-white mt-1 flex items-center gap-3 font-display">
            <span>{companyName}</span>
            <span className="vs-badge inline-flex items-center justify-center w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 text-white text-[10px] font-black shadow-lg shadow-indigo-600/30">
              VS
            </span>
            <span className="gradient-text-vivid">{competitorName}</span>
          </h2>
        </div>

        {/* Tab Toggle */}
        <div className="flex items-center bg-white/[0.03] p-1 rounded-xl border border-white/[0.04] text-xs">
          <button
            onClick={() => setActiveTab('matrix')}
            className={`px-3.5 py-2 rounded-lg font-medium transition-all duration-300 ${
              activeTab === 'matrix' ? 'btn-gradient shadow-md' : 'text-slate-500 hover:text-slate-300'
            }`}
          >
            Advantages & Gaps
          </button>
          <button
            onClick={() => setActiveTab('report')}
            className={`px-3.5 py-2 rounded-lg font-medium transition-all duration-300 ${
              activeTab === 'report' ? 'btn-gradient shadow-md' : 'text-slate-500 hover:text-slate-300'
            }`}
          >
            Executive Brief
          </button>
          <button
            onClick={() => setActiveTab('notes')}
            className={`px-3.5 py-2 rounded-lg font-medium transition-all duration-300 ${
              activeTab === 'notes' ? 'btn-gradient shadow-md' : 'text-slate-500 hover:text-slate-300'
            }`}
          >
            Strategic Notes
          </button>
        </div>
      </div>

      {activeTab === 'matrix' ? (
        <div className="space-y-6 animate-fade-in-up">
          {/* Dual Company Battle Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Your Company Card */}
            <div className="card-3d rounded-xl p-4 space-y-2 bg-white/[0.02] border border-indigo-500/15 neon-border">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold text-indigo-300 flex items-center gap-1.5 uppercase tracking-wider">
                  <Award className="w-3.5 h-3.5 text-indigo-400" /> Your Company
                </span>
                <TrendingUp className="w-4 h-4 text-emerald-400" />
              </div>
              <p className="text-sm font-bold text-white font-display">{companyName}</p>
              <a
                href={companyUrl}
                target="_blank"
                rel="noreferrer"
                className="text-[11px] text-indigo-400 hover:underline flex items-center gap-1 font-mono truncate transition-colors hover:text-indigo-300"
              >
                {companyUrl} <ExternalLink className="w-3 h-3 flex-shrink-0" />
              </a>
            </div>

            {/* Competitor Card */}
            <div className="card-3d rounded-xl p-4 space-y-2 bg-white/[0.02] border border-rose-500/15 neon-rose">
              <div className="flex items-center justify-between">
                <span className="text-[10px] font-bold text-rose-300 flex items-center gap-1.5 uppercase tracking-wider">
                  <Building2 className="w-3.5 h-3.5 text-rose-400" /> Competitor
                </span>
                <TrendingDown className="w-4 h-4 text-rose-400" />
              </div>
              <p className="text-sm font-bold text-white font-display">{competitorName}</p>
              <a
                href={competitorUrl}
                target="_blank"
                rel="noreferrer"
                className="text-[11px] text-rose-400 hover:underline flex items-center gap-1 font-mono truncate transition-colors hover:text-rose-300"
              >
                {competitorUrl} <ExternalLink className="w-3 h-3 flex-shrink-0" />
              </a>

              {/* Technographics Tech Stack Badges */}
              {technographics.length > 0 && (
                <div className="pt-2 border-t border-white/[0.04]">
                  <p className="text-[9px] font-semibold text-slate-500 uppercase tracking-wider mb-1">
                    Detected Tech Stack ({technographics.length})
                  </p>
                  <div className="flex flex-wrap gap-1">
                    {technographics.map((tech, tIdx) => (
                      <span
                        key={tIdx}
                        className="px-1.5 py-0.5 rounded bg-indigo-500/10 border border-indigo-500/20 text-[9px] font-mono text-indigo-300"
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Advantages vs Disadvantages */}
          {(() => {
            // Dynamically extract real Advantages and Gaps from the report summary
            const extractedAdvantages = extractBulletPointsFromSection(reportSummary, ['Key Advantages', 'Advantages', 'Wins']);
            const extractedGaps = extractBulletPointsFromSection(reportSummary, ['Key Disadvantages', 'Gaps', 'Disadvantages', 'Address']);

            // Fallback points dynamically tailored to the selected competitor
            const defaultAdvantages = [
              {
                title: 'Faster Onboarding & Implementation:',
                body: `Lower time-to-value for development teams compared to ${competitorName}'s setup process.`,
                strength: 85,
              },
              {
                title: 'Predictable Pricing Model:',
                body: `User-based tiers and spend controls tailored for cost predictability against ${competitorName}.`,
                strength: 78,
              },
              {
                title: 'Modern Architecture:',
                body: 'Native multi-agent background orchestration and instant automated intelligence reports.',
                strength: 92,
              },
              {
                title: 'Responsive Customer Support:',
                body: 'Faster response SLAs and direct support channel access for engineering teams.',
                strength: 70,
              },
            ];

            const defaultGaps = [
              {
                title: `${competitorName} Market Positioning:`,
                body: `${competitorName} maintains targeted positioning and web assets across ${selectedCompetitor.domain || competitorName}.`,
                gap: 65,
              },
              {
                title: 'Ecosystem & Integration Footprint:',
                body: `${competitorName} leverages specific tech stack integrations (${technographics.slice(0, 3).join(', ') || 'third-party APIs'}).`,
                gap: 55,
              },
              {
                title: 'Specialized Vertical Capabilities:',
                body: `${competitorName} highlights targeted feature sets and specialized deployment options for its user base.`,
                gap: 45,
              },
            ];

            const advantageItems = extractedAdvantages.length > 0
              ? extractedAdvantages.map((bullet, idx) => {
                  const parts = bullet.split(':');
                  const title = parts.length > 1 ? parts[0].replace(/\*\*/g, '').trim() + ':' : `Advantage ${idx + 1}:`;
                  const body = parts.length > 1 ? parts.slice(1).join(':').replace(/\*\*/g, '').trim() : bullet.replace(/\*\*/g, '').trim();
                  return { title, body, strength: Math.max(65, 95 - idx * 8) };
                })
              : defaultAdvantages;

            const gapItems = extractedGaps.length > 0
              ? extractedGaps.map((bullet, idx) => {
                  const parts = bullet.split(':');
                  const title = parts.length > 1 ? parts[0].replace(/\*\*/g, '').trim() + ':' : `Gap ${idx + 1}:`;
                  const body = parts.length > 1 ? parts.slice(1).join(':').replace(/\*\*/g, '').trim() : bullet.replace(/\*\*/g, '').trim();
                  return { title, body, gap: Math.max(45, 75 - idx * 10) };
                })
              : defaultGaps;

            return (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                {/* Advantages Column */}
                <div className="rounded-xl p-5 space-y-4 bg-emerald-500/[0.03] border border-emerald-500/10 neon-emerald">
                  <div className="flex items-center justify-between border-b border-emerald-500/10 pb-3">
                    <h3 className="text-xs font-bold text-emerald-300 flex items-center gap-2 font-display">
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                      Key Advantages ({advantageItems.length})
                    </h3>
                    <span className="text-[10px] bg-emerald-500/10 text-emerald-400 px-2.5 py-0.5 rounded-lg font-semibold">
                      Wins
                    </span>
                  </div>
                  <ul className="space-y-3 text-xs text-slate-300">
                    {advantageItems.map((point, idx) => (
                      <li key={idx} style={{ '--i': idx }} className="stagger-item space-y-1.5">
                        <div className="flex items-start gap-2.5">
                          <div className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                          <div>
                            <strong className="text-slate-100">{point.title}</strong> {point.body}
                          </div>
                        </div>
                        {/* Strength bar */}
                        <div className="ml-4 progress-bar">
                          <div className="progress-bar-fill" style={{ width: `${point.strength}%`, background: 'linear-gradient(90deg, #10b981, #34d399)' }} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Disadvantages Column */}
                <div className="rounded-xl p-5 space-y-4 bg-amber-500/[0.03] border border-amber-500/10 neon-amber">
                  <div className="flex items-center justify-between border-b border-amber-500/10 pb-3">
                    <h3 className="text-xs font-bold text-amber-300 flex items-center gap-2 font-display">
                      <AlertTriangle className="w-4 h-4 text-amber-400" />
                      Gaps vs {competitorName} ({gapItems.length})
                    </h3>
                    <span className="text-[10px] bg-amber-500/10 text-amber-400 px-2.5 py-0.5 rounded-lg font-semibold">
                      Address
                    </span>
                  </div>
                  <ul className="space-y-3 text-xs text-slate-300">
                    {gapItems.map((point, idx) => (
                      <li key={idx} style={{ '--i': idx }} className="stagger-item space-y-1.5">
                        <div className="flex items-start gap-2.5">
                          <div className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                          <div>
                            <strong className="text-slate-100">{point.title}</strong> {point.body}
                          </div>
                        </div>
                        {/* Gap bar */}
                        <div className="ml-4 progress-bar">
                          <div className="progress-bar-fill" style={{ width: `${point.gap}%`, background: 'linear-gradient(90deg, #f59e0b, #fbbf24)' }} />
                        </div>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            );
          })()}
        </div>
      ) : activeTab === 'report' ? (
        /* Executive Report View with Audio Listener */
        <div className="bg-white/[0.02] border border-white/[0.04] rounded-xl p-6 text-xs text-slate-300 max-h-[520px] overflow-y-auto animate-fade-in-up space-y-4">
          {reportSummary ? (
            <>
              {/* Executive Brief Audio Player Bar */}
              <div className="flex items-center justify-between p-3.5 rounded-xl bg-indigo-500/[0.06] border border-indigo-500/20 shadow-md">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-indigo-500/20 text-indigo-400">
                    <Headphones className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-white font-display flex items-center gap-2">
                      <span>Executive Brief Audio Listener</span>
                      {isPlayingAudio && !isPausedAudio && (
                        <span className="flex h-2 w-2 relative">
                          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
                          <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500" />
                        </span>
                      )}
                    </h4>
                    <p className="text-[10px] text-slate-400 mt-0.5">
                      {isPlayingAudio && !isPausedAudio
                        ? 'Reading executive brief aloud...'
                        : isPausedAudio
                        ? 'Audio brief playback paused'
                        : 'Listen to AI-synthesized audio briefing'}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleSpeakBrief}
                    className={`flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all duration-300 shadow-lg ${
                      isPlayingAudio && !isPausedAudio
                        ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                        : isPausedAudio
                        ? 'bg-indigo-500/20 text-indigo-300 border border-indigo-500/30'
                        : 'bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white shadow-indigo-600/30'
                    }`}
                  >
                    {isPlayingAudio && !isPausedAudio ? (
                      <>
                        <Pause className="w-3.5 h-3.5 text-amber-400" />
                        <span>Pause</span>
                      </>
                    ) : isPausedAudio ? (
                      <>
                        <Play className="w-3.5 h-3.5 text-indigo-400" />
                        <span>Resume</span>
                      </>
                    ) : (
                      <>
                        <Volume2 className="w-3.5 h-3.5 text-white" />
                        <span>Listen to Brief</span>
                      </>
                    )}
                  </button>

                  <button
                    onClick={handleMailBrief}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-violet-500/10 hover:bg-violet-600 text-violet-300 hover:text-white border border-violet-500/20 transition-all duration-200 hover:scale-105 active:scale-95 shadow-md"
                    title="Open Email Client with Executive Brief"
                  >
                    <Mail className="w-3.5 h-3.5 text-violet-400" />
                    <span>Mail Brief</span>
                  </button>

                  {(isPlayingAudio || isPausedAudio) && (
                    <button
                      onClick={handleStopAudio}
                      className="p-1.5 rounded-xl bg-white/[0.04] hover:bg-white/[0.08] text-slate-400 hover:text-white transition-colors"
                      title="Stop Audio Playback"
                    >
                      <Square className="w-3.5 h-3.5 text-rose-400" />
                    </button>
                  )}
                </div>
              </div>

              {renderMarkdownFormatted(reportSummary)}
            </>
          ) : (
            <div className="text-center py-12 space-y-3">
              <div className="w-14 h-14 rounded-2xl bg-white/[0.02] border border-white/[0.04] flex items-center justify-center mx-auto">
                <FileText className="w-7 h-7 text-slate-700" />
              </div>
              <p className="text-xs text-slate-500 font-medium">No report generated yet</p>
              <p className="text-[10px] text-slate-600">Run the intelligence pipeline to generate a full executive brief.</p>
            </div>
          )}
        </div>
      ) : (
        <CompetitorNotes selectedCompetitor={selectedCompetitor} />
      )}
    </div>
  );
}

function renderMarkdownFormatted(mdText) {
  if (!mdText) return null;
  const lines = mdText.split('\n');
  const elements = [];
  let inTable = false;
  let tableRows = [];

  const flushTable = (key) => {
    if (tableRows && tableRows.length > 0) {
      const headerRow = tableRows[0] || [];
      const bodyRows = (tableRows.slice(1) || []).filter(
        (r) => r && Array.isArray(r) && !r.every((c) => (c || '').trim().startsWith('-'))
      );
      elements.push(
        <div key={key} className="overflow-x-auto my-4 border border-white/[0.06] rounded-xl shadow-lg">
          <table className="w-full text-left text-xs">
            <thead className="bg-white/[0.03] text-indigo-300 border-b border-white/[0.04] font-semibold">
              <tr>
                {(Array.isArray(headerRow) ? headerRow : []).map((cell, idx) => (
                  <th key={idx} className="p-3">{(cell || '').replace(/\*\*/g, '').trim()}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-white/[0.03]">
              {(Array.isArray(bodyRows) ? bodyRows : []).map((row, rIdx) => (
                <tr key={rIdx} className="hover:bg-white/[0.02] transition">
                  {(Array.isArray(row) ? row : []).map((cell, cIdx) => (
                    <td key={cIdx} className="p-3 text-slate-300">{(cell || '').replace(/\*\*/g, '').trim()}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
      tableRows = [];
    }
    inTable = false;
  };

  lines.forEach((line, idx) => {
    const trimmed = line.trim();
    if (trimmed.startsWith('|') && trimmed.endsWith('|')) {
      inTable = true;
      const cells = trimmed.split('|').slice(1, -1);
      tableRows.push(cells);
    } else {
      if (inTable) flushTable(`table-${idx}`);
      if (trimmed.startsWith('## ')) {
        elements.push(
          <h3 key={idx} className="text-sm font-bold text-indigo-400 mt-5 mb-2 font-display border-b border-white/[0.04] pb-1.5 flex items-center gap-2">
            {trimmed.replace('## ', '')}
          </h3>
        );
      } else if (trimmed.startsWith('# ')) {
        elements.push(
          <h2 key={idx} className="text-base font-extrabold text-white mt-2 mb-3 font-display">
            {trimmed.replace('# ', '')}
          </h2>
        );
      } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const text = trimmed.replace(/^[-*]\s+/, '');
        elements.push(
          <div key={idx} className="text-xs text-slate-300 my-1.5 flex items-start gap-2.5">
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 mt-1.5 shrink-0" />
            <span>{text.replace(/\*\*(.*?)\*\*/g, '$1')}</span>
          </div>
        );
      } else if (trimmed && trimmed !== '---') {
        elements.push(
          <p key={idx} className="text-xs text-slate-300 my-2 leading-relaxed">
            {trimmed.replace(/\*\*(.*?)\*\*/g, '$1')}
          </p>
        );
      }
    }
  });

  if (inTable) flushTable('table-end');
  return elements;
}