import { useState, useEffect, useCallback } from 'react';
import { NotebookPen, Save, Copy, Download, Trash2, Check, Tag, Clock, Sparkles, Mail } from 'lucide-react';
import { useToast } from '../contexts/ToastContext';

const QUICK_TAGS = [
  { label: 'Pricing Strategy', tag: '[PRICING STRATEGY]: ' },
  { label: 'Feature Gap', tag: '[FEATURE GAP]: ' },
  { label: 'Winning Angle', tag: '[WINNING ANGLE]: ' },
  { label: 'Action Item', tag: '[ACTION ITEM]: ' },
  { label: 'Executive Note', tag: '[EXECUTIVE NOTE]: ' },
];

export default function CompetitorNotes({ selectedCompetitor }) {
  const toast = useToast();
  const compId = selectedCompetitor?.id || 'global';
  const compName = selectedCompetitor?.name || 'General Workspace';
  const storageKey = `ci_notes_${compId}`;

  const [noteText, setNoteText] = useState('');
  const [lastSaved, setLastSaved] = useState(null);
  const [isCopied, setIsCopied] = useState(false);
  const [isSavedRecently, setIsSavedRecently] = useState(false);

  // Load saved note when selectedCompetitor changes
  useEffect(() => {
    try {
      const saved = localStorage.getItem(storageKey);
      if (saved) {
        const parsed = JSON.parse(saved);
        setNoteText(parsed.text || '');
        setLastSaved(parsed.updatedAt || null);
      } else {
        setNoteText('');
        setLastSaved(null);
      }
    } catch (e) {
      console.error('Failed to load notes from localStorage:', e);
      setNoteText('');
    }
  }, [storageKey]);

  // Save handler
  const saveNote = useCallback((textToSave) => {
    try {
      const timestamp = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      const payload = { text: textToSave, updatedAt: timestamp };
      localStorage.setItem(storageKey, JSON.stringify(payload));
      setLastSaved(timestamp);
      setIsSavedRecently(true);
      setTimeout(() => setIsSavedRecently(false), 2000);
    } catch (e) {
      console.error('Failed to save notes:', e);
    }
  }, [storageKey]);

  // Handle textarea change with auto-save
  const handleChange = (e) => {
    const val = e.target.value;
    setNoteText(val);
    saveNote(val);
  };

  // Manual save trigger with Toast notification
  const handleManualSave = () => {
    saveNote(noteText);
    toast.success(`Notes saved for ${compName}`, 'Notes Saved');
  };

  // Copy to clipboard
  const handleCopy = () => {
    if (!noteText.trim()) return;
    navigator.clipboard.writeText(noteText);
    setIsCopied(true);
    toast.success('Notes copied to clipboard!');
    setTimeout(() => setIsCopied(false), 2000);
  };

  // Open default email client with notes pre-filled
  const handleMailNotes = () => {
    if (!noteText.trim()) return;
    const subject = `Strategic Intelligence Notes: ${compName}`;
    const body = `Strategic Notes for ${compName}:\n\n${noteText}\n\n---\nGenerated by Autonomous Competitive Intelligence Agent Network`;
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    toast.info(`Navigating to default email app...`, 'Email Client Launched');
  };

  // Export as .txt download
  const handleDownload = () => {
    if (!noteText.trim()) return;
    const blob = new Blob([`# Intelligence Notes: ${compName}\n# Saved on: ${new Date().toLocaleString()}\n\n${noteText}`], {
      type: 'text/plain;charset=utf-8',
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${compName.toLowerCase().replace(/\s+/g, '-')}-intelligence-notes.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.info(`Downloaded notes as text file`, 'Notes Exported');
  };

  // Clear note
  const handleClear = () => {
    if (!noteText.trim()) return;
    if (window.confirm(`Are you sure you want to clear notes for ${compName}?`)) {
      setNoteText('');
      localStorage.removeItem(storageKey);
      setLastSaved(null);
      toast.info('Notes cleared.');
    }
  };

  // Insert Quick Tag
  const handleInsertTag = (tag) => {
    const newText = noteText ? `${noteText.trim()}\n${tag}` : tag;
    setNoteText(newText);
    saveNote(newText);
  };

  return (
    <div className="glass-card rounded-2xl p-5 neon-border space-y-4 animate-fade-in-up">
      {/* Header & Controls */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-white/[0.04] pb-3">
        <div>
          <h2 className="text-sm font-bold text-white flex items-center gap-2 font-display">
            <div className="p-1.5 rounded-lg bg-indigo-500/10">
              <NotebookPen className="w-4 h-4 text-indigo-400" />
            </div>
            <span>Strategic Notes & Key Takeaways</span>
          </h2>
          <p className="text-[10px] text-slate-500 mt-0.5">
            Auto-saved notes for <span className="text-indigo-400 font-semibold">{compName}</span>
          </p>
        </div>

        {/* Action Controls */}
        <div className="flex items-center gap-2 text-xs">
          {lastSaved && (
            <span className="text-[10px] text-slate-500 flex items-center gap-1 font-mono mr-1">
              <Clock className="w-3 h-3 text-slate-600" /> {isSavedRecently ? 'Saved just now' : `Saved ${lastSaved}`}
            </span>
          )}

          <button
            onClick={handleManualSave}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-indigo-500/10 hover:bg-indigo-600 text-indigo-300 hover:text-white border border-indigo-500/20 text-[10px] font-semibold transition-all duration-200 hover:scale-105 active:scale-95"
            title="Save Notes"
          >
            <Save className="w-3 h-3" />
            <span>Save</span>
          </button>

          <button
            onClick={handleCopy}
            disabled={!noteText.trim()}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-white/[0.03] hover:bg-white/[0.08] text-slate-300 hover:text-white border border-white/[0.06] text-[10px] font-semibold transition-all duration-200 hover:scale-105 disabled:opacity-40"
            title="Copy Notes"
          >
            {isCopied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
            <span>{isCopied ? 'Copied' : 'Copy'}</span>
          </button>

          <button
            onClick={handleMailNotes}
            disabled={!noteText.trim()}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-violet-500/10 hover:bg-violet-600 text-violet-300 hover:text-white border border-violet-500/20 text-[10px] font-semibold transition-all duration-200 hover:scale-105 disabled:opacity-40"
            title="Open Default Email App with Notes"
          >
            <Mail className="w-3 h-3 text-violet-400" />
            <span className="hidden sm:inline">Mail</span>
          </button>

          <button
            onClick={handleDownload}
            disabled={!noteText.trim()}
            className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-emerald-500/10 hover:bg-emerald-600 text-emerald-300 hover:text-white border border-emerald-500/20 text-[10px] font-semibold transition-all duration-200 hover:scale-105 disabled:opacity-40"
            title="Download Notes (.txt)"
          >
            <Download className="w-3 h-3" />
            <span className="hidden sm:inline">Export</span>
          </button>

          <button
            onClick={handleClear}
            disabled={!noteText.trim()}
            className="p-1.5 rounded-lg bg-white/[0.03] hover:bg-rose-500/20 text-slate-400 hover:text-rose-300 border border-white/[0.06] text-[10px] transition-all duration-200 disabled:opacity-40"
            title="Clear Notes"
          >
            <Trash2 className="w-3 h-3" />
          </button>
        </div>
      </div>

      {/* Quick Tag Pills */}
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="text-[10px] text-slate-500 font-semibold uppercase tracking-wider flex items-center gap-1 mr-1">
          <Tag className="w-3 h-3 text-indigo-400" /> Quick Tags:
        </span>
        {QUICK_TAGS.map((t, idx) => (
          <button
            key={idx}
            onClick={() => handleInsertTag(t.tag)}
            className="px-2 py-0.5 rounded-md bg-white/[0.03] hover:bg-indigo-500/15 border border-white/[0.06] text-[10px] font-mono text-slate-300 hover:text-indigo-300 transition-all duration-150 hover:scale-105"
          >
            + {t.label}
          </button>
        ))}
      </div>

      {/* Textarea Input */}
      <div className="relative">
        <textarea
          value={noteText}
          onChange={handleChange}
          rows={5}
          placeholder={`Type strategic notes, competitor vulnerabilities, or action items for ${compName}...`}
          className="w-full bg-white/[0.02] border border-white/[0.06] rounded-xl p-3.5 text-xs text-slate-100 placeholder-slate-600 focus:outline-none focus:border-indigo-500/40 font-sans leading-relaxed resize-y input-glow"
        />
        {isSavedRecently && (
          <span className="absolute bottom-3 right-3 text-[10px] text-emerald-400 font-mono flex items-center gap-1 bg-emerald-500/10 border border-emerald-500/20 px-2 py-0.5 rounded-md animate-scale-in">
            <Sparkles className="w-3 h-3" /> Auto-saved
          </span>
        )}
      </div>
    </div>
  );
}
